apiVersion: batch/v1
kind: Job
metadata:
  name: etl-job
spec:
  template:
    spec:
      containers:
      - name: etl
        image: python:3.10
        command: ["sh", "-c"]
        args:
          - |
            pip install pandas numpy && \
            curl -O https://raw.githubusercontent.com/Sudharshan2108/Databricks-CI-CD_Pipeline/main/etl.py && \
            python etl.py
      restartPolicy: Never
